const IMAGES = {
    bettu: new URL('./bettu.png', import.meta.url).href,
    raebin: new URL('./raebin.png', import.meta.url).href,
    kakao_login: new URL('./kakao_login.png', import.meta.url).href,
    비즈니스: new URL('./비즈니스.png', import.meta.url).href,
    일상: new URL('./일상.png', import.meta.url).href,
    취미: new URL('./취미.png', import.meta.url).href,
    여행: new URL('./여행.png', import.meta.url).href,
    English: new URL('./americanFlag.png', import.meta.url).href,
    한국어: new URL('./koreaFlag.png', import.meta.url).href,
    mypage: new URL('./mypage.png', import.meta.url).href,
    여행_준비: new URL('./여행준비.png', import.meta.url).href,
    학업: new URL('./학업.png', import.meta.url).href,
    생산적인_시간_활동: new URL('./생산적인시간활동.png', import.meta.url).href,
    사람들과_소통: new URL('./사람들과소통.png', import.meta.url).href,
    경력_개발: new URL('./경력개발.png', import.meta.url).href,
    취미_활동: new URL('./취미.png', import.meta.url).href,
    기타: new URL('./기타.png', import.meta.url).href,
    sendMessage: new URL('./sendMessage.png', import.meta.url).href,
    time0: new URL('./time0.png', import.meta.url).href,
    time10: new URL('./time10.png', import.meta.url).href,
    time30: new URL('./time30.png', import.meta.url).href,
    time60: new URL('./time60.png', import.meta.url).href,
    time120: new URL('./time120.png', import.meta.url).href,
    after10days: new URL('./after10days.png', import.meta.url).href,
    after30days: new URL('./after30days.png', import.meta.url).href,
    베튜말풍선: new URL('./베튜말풍선.png', import.meta.url).href,
    start: new URL('./start.png', import.meta.url).href,
    global: new URL('./global.png', import.meta.url).href,
    scrollButtonLeft: new URL('./scrollButtonLeft.png', import.meta.url).href,
    scrollButtonRight: new URL('./scrollButtonRight.png', import.meta.url).href
};

export default IMAGES;